# Generated by Django 2.0.6 on 2018-06-29 01:15

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

#NOT VALID, SYNC DJANGO AND FIX

class Migration(migrations.Migration):

    initial = True

migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('day', models.CharField(max_length=30, verbose_name='Day'))
                ('month', models.CharField(max_length=30, verbose_name='Month')),
                ('year', models.SmallIntegerField(blank=True, verbose_name='Year')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(4000, 2, 21, 10, 28, 45), verbose_name='Publication Date')),
                ('pdf', models.FileField(blank=True, upload_to='pdf/notepad/notes', verbose_name='PDF')),
            ],
            options={
                'ordering': ['note'],
            },
        ),